# 1D array examples

In [2]:
import numpy as np

np.arange(0,15)  # creating an 1D arary from 0 to 15.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
np.arange(1,16) # this will print from 1 to 15 digits of 1D array.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## Slice like python list

In [4]:
one_d_arr = np.arange(1,16) # assiging 1D array to 'one_d_arr' variable.

one_d_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
one_d_arr[1] # 1 is the index postion so it will 2 because the index start's from Zero. 

# So 1 is in index 0  where 2 is in index 1 and 3 in is in index of 2 and so on.

2

In [7]:
one_d_arr[0:5]  #. 0 is start and 5 is end

# so it will return digits b/w 0 to 4

array([1, 2, 3, 4, 5])

In [10]:
# the above line also can be written like

one_d_arr[:5]  

array([1, 2, 3, 4, 5])

In [11]:
one_d_arr[5:8]  # numbers from index position 5 to index posting 7 will print

array([6, 7, 8])

In [12]:
one_d_arr[0:8:2]  # 0 is start,  8 is end  and 2 is step

array([1, 3, 5, 7])

## Changing the value of an array using slicing

In [13]:
one_d_arr[0:5]

array([1, 2, 3, 4, 5])

In [15]:
one_d_arr[0:5] = 300

one_d_arr   # the first 0 to 5 numbers are changed with 300.

array([300, 300, 300, 300, 300,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15])

In [18]:
one_d_arr[0:10:2] = 500

one_d_arr

array([500, 300, 500, 300, 500,   6, 500,   8, 500,  10,  11,  12,  13,
        14,  15])

## Array Copy function

The copy function will make dublicate copy of original array. 
If you do any changes on the copied array it will not effect the original array

In [19]:
original_array = np.arange(1,25)
original_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [22]:
# coping original array to copy_array variable

copy_array = original_array.copy()

copy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [27]:
# the both have same elements
# now i am chainging the copy_array

copy_array[0:10:2] = 300

copy_array

array([300,   2, 300,   4, 300,   6, 300,   8, 300,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [29]:
# this change will not effect the original array

original_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

# 2D Array

In [31]:
# Python 2 Dim List

l1 = [[1,2,3],[4,5,6],[7,8,9]]

# Converting 2Dim List to numpy array

import numpy as np

two_d_array = np.array(l1)

two_d_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
# Creating 2Dim array using arange() function

two_d_array = np.arange(50)

two_d_array.reshape(5,10)  

# Note : when we reshape the array is converted into 2Dim array.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [44]:
# simple 3/3 Matrix example

two_dim = np.arange(1,10).reshape(3,3)

two_dim


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
# Index positions of 2 Dim array.

# 1st we pick row then we pick col

# Note : index will start from zero

two_dim[1] 

array([4, 5, 6])

In [48]:
two_dim[0]

array([1, 2, 3])

In [51]:
two_dim[0][2]

#  0 - row.  2 - col
# 0th row of 2nd col

3

In [52]:
two_d_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [53]:
# reshaping 2D array

two_dim = two_d_array.reshape(5,10)

two_dim

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [54]:
# using index postitions on 5/10

# to print 25

two_dim[2]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [55]:
two_dim[2][5]

25

In [58]:
# till now what we did we can do on python as well. (like index)

# In Numpy

two_dim[2,5]  # very simple in Numpy  

# understanding the 1st param is row and 2 param is col
# note we can apply slice as well


25

In [59]:
two_dim[1:4,]  # slicing on rows only

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [60]:
two_dim[:,1:5]  # slicing on cols only

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [62]:
two_dim[1:4,2:5]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])