# Linear Algebra

✅ What is Linear Algebra?

Linear algebra is the branch of mathematics that deals with:

1. Vectors

2. Matrices

3. Linear transformations

4. Systems of linear equations

📌 It is the foundation of machine learning, computer graphics, engineering, and data science.

## 🧱 1. Scalars, Vectors, Matrices, Tensors

| Term   | Definition                           | Example                      |
| ------ | ------------------------------------ | ---------------------------- |
| Scalar | A single number                      | `5`, `-3.2`                  |
| Vector | A list of numbers (1D array)         | `[2, 3, -1]`                 |
| Matrix | A grid of numbers (2D array)         | `[[1, 2], [3, 4]]`           |
| Tensor | Multi-dimensional array (3D or more) | e.g., image data `[3x28x28]` |


# Example's 
## Scalars

In [3]:

# Scalar means a single number

age = 23

salary = 10000.00

idno = 'NPW88456'

print(f"Employee Age is {age}")

print(f"Employee Salary is {salary}")

print(f"Employee Idno is {idno}")

Employee Age is 23
Employee Salary is 10000.0
Employee Idno is NPW88456


## Vectors

In [4]:
# Vectors are 1Dim arrays.

# a list of employee id's

idnos = [101,102,103,104,105]

print(idnos)

[101, 102, 103, 104, 105]


In [6]:
# Vectors using Numpy

# Converting python list into Numpy 1D array

import numpy as np

np.array(idnos)


array([101, 102, 103, 104, 105])

In [8]:
# we can assing it to a variable

numpy_idnos = np.array(idnos)

numpy_idnos

array([101, 102, 103, 104, 105])

In [10]:
# We can use numpy built in functions to create 1Dim array

one_d_array = np.arange(1,11)

one_d_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Matrices

In [12]:
# Matrices are 2Dim Arrays.

# List of employee details in python.

employee_details = [
    [101,10000.00],
    [102,12000.00],
    [103,11000.00]
]

employee_details

[[101, 10000.0], [102, 12000.0], [103, 11000.0]]

In [17]:
# Converting List into numpy array's

two_d_array = np.array(employee_details)

print(two_d_array)

print(two_d_array.shape)

[[  101. 10000.]
 [  102. 12000.]
 [  103. 11000.]]
(3, 2)


## Tensor

In [18]:
tensor_3d = np.array([
    [
        [1, 2], 
        [3, 4],
        [5, 6]
    ],
    [
        [9, 10], 
        [7, 8],
        [11, 12]
    ]
])
print("\n3D Tensor:\n", tensor_3d)
print("Shape:", tensor_3d.shape)


3D Tensor:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 9 10]
  [ 7  8]
  [11 12]]]
Shape: (2, 3, 2)


# What is Linear transformations ?

A linear transformation is a math rule that:

1. Stretches

2. Shrinks

3. Rotates

4. Flips

It keeps lines straight and the center fixed.

And it's done using a matrix × vector like this:

### new_vector = matrix × old_vector

## 🧱 In Numbers (Simple 2D Example)

Let’s say you have a point:

x = [2, 3]

Now you apply this transformation (multiply each number by 2):


x becomes → [4, 6]

So the point is moved further away from the center (origin). 

This is a scaling linear transformation.

## 🖼 Think of It Like a Photo Filter

Imagine you have a photo full of arrows.

A linear transformation is like putting a filter over it that:

Stretches, rotates, or flips all the arrows.

But doesn’t break the shape of lines or curves.

And always keeps the origin (0,0) in the same place

## 💡 Important: It Must Follow 2 Simple Rules

1. Adding arrows then transforming should be same as transforming then adding (lines stay straight)

2. Doubling an arrow before transformation = doubling the transformed arrow (scaling works the same)

## 🧪 Real World Example

You're designing a game.

You have a spaceship flying at [1, 2] speed.

Now you want a "boost" button that doubles speed.

That’s a linear transformation:

[1, 2] → [2, 4]

You just scaled the motion — same direction, just faster. 🚀

![Alt Text](images/Scaling.jpg)  

### Here's a visual example of linear transformations:

Left: Scaling by 2 — stretches all vectors away from the origin.

Middle: Rotating by 90° — turns the vectors counter-clockwise.

Right: Reflection over the x-axis — flips the vectors vertically.

Blue arrows = original vectors

Red arrows = transformed vectors

This shows how matrices reshape space by transforming all vectors consistently — the core idea of linear transformation.

## Examples

### 🔷 1. Stretches (e.g. Stretch along x-axis)

Stretch a vector by 3x along x-axis (y stays same):

In [25]:
import numpy as np

v = np.array([[2],
              [1]])

# Stretching matrix (stretch x by 3)
T = np.array([[3, 0],
              [0, 1]])

v_stretched = np.dot(T, v)

print("Stretched:\n", v_stretched)


Stretched:
 [[6]
 [1]]


### 🔷 2. Shrinks (e.g. Shrink along y-axis)

Shrink vector by 0.5x on y-axis (x stays same):

In [26]:
v = np.array([[2],
              [4]])

# Shrinking matrix (shrink y by 0.5)
T = np.array([[1, 0],
              [0, 0.5]])

v_shrunk = np.dot(T, v)

print("Shrunk:\n", v_shrunk)


Shrunk:
 [[2.]
 [2.]]


### 🔷 3. Rotates (90° counterclockwise)

Rotate a vector by 90° counterclockwise:

Counter-clockwise (also written as anticlockwise) means rotating in the opposite direction of a clock’s hands.

In [27]:
v = np.array([[1],
              [0]])

# Rotation matrix (90 degrees CCW)
T = np.array([[0, -1],
              [1,  0]])

v_rotated = np.dot(T, v)

print("Rotated:\n", v_rotated)


Rotated:
 [[0]
 [1]]


### 🔷 4. Flips (reflect across x-axis)

Flip (reflect) a vector over the x-axis:

In [28]:
v = np.array([[3],
              [2]])

# Reflection matrix across x-axis
T = np.array([[1,  0],
              [0, -1]])

v_flipped = np.dot(T, v)

print("Flipped:\n", v_flipped)


Flipped:
 [[ 3]
 [-2]]


### Summary 

| Transformation | Matrix               | Effect            |
| -------------- | -------------------- | ----------------- |
| Stretch        | `[[3, 0], [0, 1]]`   | Stretch x, keep y |
| Shrink         | `[[1, 0], [0, 0.5]]` | Shrink y, keep x  |
| Rotate (90°)   | `[[0, -1], [1, 0]]`  | Rotate left (CCW) |
| Flip (x-axis)  | `[[1, 0], [0, -1]]`  | Flip vertically   |


# What is a Linear Equation?

A linear equation is like:

### something × x + something = something
## or
### Some number times x, plus or minus something, equals a number.

It helps us find unknown values.


### 2x + 3 = 7

This is a linear equation. Why?

1. It has x (a variable).

2. No powers (no x² or x³).

3. Just simple addition and multiplication.

### 💡 Goal: Find the value of x

Solve step-by-step:

1. Start with: 2x + 3 = 7

2. Subtract 3 from both sides:  2x = 4

3. Divide both sides by 2:  x = 2

🎉 So, x = 2 is the answer!


### 🧠 Why do we subtract 3?

In 2x + 3 = 7, the + 3 is added to 2x.

To remove it, we do the opposite, which is subtract 3.

👉 We subtract 3 from both sides of the =.

### ✏️ Like this:

#####  2x + 3  =  7         ← original equation
#####         -3    -3       ← subtract 3 from both sides
##### ------------------
#####         2x  =   4


Now it’s much simpler! Just divide both sides by 2 to find x:

x = 4 ÷ 2

x = 2

### Real life Examples


#### 💼 1. Shopping Example

You buy pens for £2 each. You also pay £1 delivery.

👉 How much do you pay if you buy x pens? when you spend £11?

Linear Equation:  Total = 2x + 1

If you spend £11:  2x + 1 = 11

Solve:  

2x = 10   (subtract 1 from both sides)

x = 5     (divide by 2)

✅ You bought 5 pens



#### 🚌 2. Bus Fare Example

A bus charges £3 to start and £2 for every mile you travel.

👉 How much is the total cost if you travel x miles? when you spend £11 ?

Linear Equation:  Cost = 2x + 3

If your cost was £11:  2x + 3 = 11

Solve:

2x = 8  (subtract 3 from both sides)

x = 4 miles   (divide by 2)

✅ You traveled 4 miles



#### 🏠 5. Electricity Bill Example

Fixed charge: £15
Usage charge: £5 per unit
You paid £40. 
👉 How many units did you use?

Equation:   5x + 15 = 40

5x = 25

x = 5

✅ You used 5 units

# ✅ What is a System of Linear Equations?

### 💬 Simple definition:

A System of Linear Equations is two or more "linear equations" working together.

👉 They share the same variables (like x and y), and we want to find values that satisfy all equations at the same time.

📌 Example:

Let’s take two equations:

1) 2x + 3y = 13  

2) 4x + 9y = 37

This is called a system because:   There are two equations

We want to find values of x and y that work in both

🧠 Goal:  Find the values of x and y that make both equations true.

### 🧮 Let's solve it using NumPy

#### Step-by-step:
    
Write the left sides (coefficients) as a matrix A:

A = [[2, 3],
     [4, 9]]

Write the right side as a vector B:

B = [13, 37]

Use np.linalg.solve(A, B) to get the values of x and y.

In [30]:
import numpy as np

A = np.array([[2, 3],
              [4, 9]])

B = np.array([13, 37])

solution = np.linalg.solve(A, B)

print("x and y:", solution)

x and y: [1.         3.66666667]


### What is np.linalg.solve(A, B)?

It’s a function used to solve a system of linear equations.

If you have a system like this:

#### 𝐴  ×  𝑥 = 𝐵

A is a matrix of coefficients (numbers in front of variables)

𝑥 is a vector of unknown variables you want to find

𝐵 is a vector of constants (numbers on the right side)

np.linalg.solve(A, B) finds the values of x that satisfy the equation.

## 🎯 Real-Life Example: 

### Shopping
    
You go to a shop and buy:

2 pens and 5 pencils for £40

4 pens and 5 pencils for £90

Find the cost of 1 pen and 1 pencil.

In [36]:
# 2x + 5y = 40
# 4x + 5y = 90

A = np.array([[2,5],
             [4,5]])

B = np.array([40,90])

pen_pencil = np.linalg.solve(A,B)

print("Pen and Pencil:", pen_pencil)

Pen and Pencil: [25. -2.]


So:

1 pen costs £25

1 pencil costs £2

### Question

You buy 

3 notebooks and 2 pens for £16, and
5 notebooks and 4 pens for £34.

know the price of one notebook (n) and the price of one pen (p),

In [44]:
# 3x + 2y = 16
# 5x + 4y = 34


A = np.array([
        [3,2],
        [5,4]
    ])

B = np.array([16,34])

notebook_pen = np.linalg.solve(A,B)

print(f"Notebook and Pren = {notebook_pen}")

print(f"Notebook = £{notebook_pen[0]:.2f}")

print(f"Pen = £{notebook_pen[1]:.2f}")


Notebook and Pren = [-2. 11.]
Notebook = £-2.00
Pen = £11.00


### Question:
At your café:

2 ☕coffee cups + 3 🥪sandwiches + 1 🧁muffin cost = £25

1 ☕coffee cup + 2 🥪sandwiches + 4 🧁muffins cost = £23

3 ☕coffee cups + 1 🥪sandwich + 2 🧁muffins cost = £30

Find the price of one coffee cup, one sandwich, and one muffin.


In [52]:
# 2c + 3s + 1m = 25
# 1c + 2s + 4m = 23
# 3c + 1s + 2m = 30

A = np.array([
        [2,3,1],
        [1,2,4],
        [3,1,2]
    ])

B = np.array([25,23,30])

coffe_sand_muffin = np.linalg.solve(A,B)

print(f"Coffe Price {coffe_sand_muffin[0]:.2f}")

print(f"Sandwich Price {coffe_sand_muffin[1]:.2f}")

print(f"Muffin Proce {coffe_sand_muffin[2]:.2f}")
      
      

Coffe Price 7.40
Sandwich Price 2.52
Muffin Proce 2.64
