# Linear Algebra

✅ What is Linear Algebra?

Linear algebra is the branch of mathematics that deals with:

1. Vectors

2. Matrices

3. Linear transformations

4. Systems of linear equations

📌 It is the foundation of machine learning, computer graphics, engineering, and data science.

## 🧱 1. Scalars, Vectors, Matrices, Tensors

| Term   | Definition                           | Example                      |
| ------ | ------------------------------------ | ---------------------------- |
| Scalar | A single number                      | `5`, `-3.2`                  |
| Vector | A list of numbers (1D array)         | `[2, 3, -1]`                 |
| Matrix | A grid of numbers (2D array)         | `[[1, 2], [3, 4]]`           |
| Tensor | Multi-dimensional array (3D or more) | e.g., image data `[3x28x28]` |


1. Scalars, Vectors, and Matrices

Create and print scalars, vectors, and matrices with NumPy

2. Vector Operations

Addition, subtraction, scalar multiplication, Dot product example

3. Matrix Operations

Matrix addition, scalar multiplication, matrix multiplication, Identity matrix and transpose

4. Determinant and Inverse

Calculate determinant and inverse using NumPy

5. Practice Questions

Vector addition

Matrix multiplication

Find the inverse of a matrix

Calculate determinant

## Example's 
## Scalars

In [3]:

# Scalar means a single number

age = 23

salary = 10000.00

idno = 'NPW88456'

print(f"Employee Age is {age}")

print(f"Employee Salary is {salary}")

print(f"Employee Idno is {idno}")

Employee Age is 23
Employee Salary is 10000.0
Employee Idno is NPW88456


## Vectors

In [4]:
# Vectors are 1Dim arrays.

# a list of employee id's

idnos = [101,102,103,104,105]

print(idnos)

[101, 102, 103, 104, 105]


In [6]:
# Vectors using Numpy

# Converting python list into Numpy 1D array

import numpy as np

np.array(idnos)


array([101, 102, 103, 104, 105])

In [8]:
# we can assing it to a variable

numpy_idnos = np.array(idnos)

numpy_idnos

array([101, 102, 103, 104, 105])

In [10]:
# We can use numpy built in functions to create 1Dim array

one_d_array = np.arange(1,11)

one_d_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Matrices

In [12]:
# Matrices are 2Dim Arrays.

# List of employee details in python.

employee_details = [
    [101,10000.00],
    [102,12000.00],
    [103,11000.00]
]

employee_details

[[101, 10000.0], [102, 12000.0], [103, 11000.0]]

In [14]:
# Converting List into numpy array's

two_d_array = np.array(employee_details)

two_d_array

array([[  101., 10000.],
       [  102., 12000.],
       [  103., 11000.]])