In [7]:
# Python 1D-List

l1 = [1,2,3,4,5]

print(l1)

[1, 2, 3, 4, 5]


In [8]:
# casting python list to numpy 1D array

import numpy as np

np.array(l1) 


array([1, 2, 3, 4, 5])

In [9]:
# python 2D-List (list in a list)

l2 = [[1,2,3],[4,5,6],[7,8,9]]

print(l2)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [10]:
# casting python 2d list to numpy 2D array

np.array(l2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Note : In NumPy, a 1D array represents a vector, while a 2D array represents a matrix.

In [15]:
np.arange(0,10) # 0 is starting and 10 is ending 

# This function will create an 1D array on given start and end numbers 
# Since the number is starting from 0 it is ending at 9


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(5,15)

# Since the number is starting from 5 ending at 14

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.arange(5,15,2) # 2 is step

# since the step is 2 the array will skip 2 number -- 5,7,9,11...

array([ 5,  7,  9, 11, 13])

In [29]:
# we can use built in functions for arrays in numpy 

# zeros(), ones()

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.ones(50)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
np.linspace(5,30)  # 5 is staring and 50 is ending

# It creates a sequence of evenly spaced numbers over a specified interval.

# start: The starting value of the sequence

# stop: The end value of the sequence

# num: (Optional) Number of points to generate (default is 50)

array([ 5.        ,  5.51020408,  6.02040816,  6.53061224,  7.04081633,
        7.55102041,  8.06122449,  8.57142857,  9.08163265,  9.59183673,
       10.10204082, 10.6122449 , 11.12244898, 11.63265306, 12.14285714,
       12.65306122, 13.16326531, 13.67346939, 14.18367347, 14.69387755,
       15.20408163, 15.71428571, 16.2244898 , 16.73469388, 17.24489796,
       17.75510204, 18.26530612, 18.7755102 , 19.28571429, 19.79591837,
       20.30612245, 20.81632653, 21.32653061, 21.83673469, 22.34693878,
       22.85714286, 23.36734694, 23.87755102, 24.3877551 , 24.89795918,
       25.40816327, 25.91836735, 26.42857143, 26.93877551, 27.44897959,
       27.95918367, 28.46938776, 28.97959184, 29.48979592, 30.        ])

In [35]:
np.linspace(5,30,100)

array([ 5.        ,  5.25252525,  5.50505051,  5.75757576,  6.01010101,
        6.26262626,  6.51515152,  6.76767677,  7.02020202,  7.27272727,
        7.52525253,  7.77777778,  8.03030303,  8.28282828,  8.53535354,
        8.78787879,  9.04040404,  9.29292929,  9.54545455,  9.7979798 ,
       10.05050505, 10.3030303 , 10.55555556, 10.80808081, 11.06060606,
       11.31313131, 11.56565657, 11.81818182, 12.07070707, 12.32323232,
       12.57575758, 12.82828283, 13.08080808, 13.33333333, 13.58585859,
       13.83838384, 14.09090909, 14.34343434, 14.5959596 , 14.84848485,
       15.1010101 , 15.35353535, 15.60606061, 15.85858586, 16.11111111,
       16.36363636, 16.61616162, 16.86868687, 17.12121212, 17.37373737,
       17.62626263, 17.87878788, 18.13131313, 18.38383838, 18.63636364,
       18.88888889, 19.14141414, 19.39393939, 19.64646465, 19.8989899 ,
       20.15151515, 20.4040404 , 20.65656566, 20.90909091, 21.16161616,
       21.41414141, 21.66666667, 21.91919192, 22.17171717, 22.42

In [40]:
# identity matrix
# An identity matrix is a square matrix with 1s on the diagonal and 0s elsewhere.

np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.eye(3, 3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

Both np.eye() and np.identity() in NumPy create identity-like matrices, but they have slight differences in flexibility.

✅ np.identity(n)

Creates a square identity matrix of size n x n

Only supports square matrices

Diagonal always starts from the top-left

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
       


✅ np.eye(N, M=None, k=1)

More flexible

Can create non-square matrices

k controls the diagonal

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

## Examples on Random

In [52]:
import numpy as np

np.random.rand(5) # this will print 5 random num array

array([0.81829323, 0.28045526, 0.21246944, 0.18312605, 0.93846343])

In [54]:
# or

from numpy import random as ran

ran.rand(10) # 1D Array

array([0.81509474, 0.06407042, 0.1356833 , 0.74506137, 0.48764145,
       0.84131938, 0.00271418, 0.96667649, 0.56971391, 0.14602895])

In [55]:
ran.rand(5,5) # 2D Array

array([[0.68571594, 0.92084273, 0.19617484, 0.02450239, 0.5789261 ],
       [0.05967076, 0.02418758, 0.07054157, 0.08467137, 0.84653867],
       [0.32178375, 0.69993913, 0.6983664 , 0.50408862, 0.37960565],
       [0.72281299, 0.14632747, 0.45506317, 0.17090039, 0.84938866],
       [0.97211961, 0.34791828, 0.26281328, 0.93195089, 0.59037685]])

In [58]:
ran.randint(50) # will return 1 random number

15

In [75]:
ran.randint(5,100) # this also return 1 random number but b/w 5 and 99 only.

97

In [79]:
ran.randint(5,100,15) # this will retun an 1D array of random numbers

# 5 is start
# 100 is end
# 15 is size

array([59, 80, 35, 28,  7, 46, 83, 36, 74, 22, 85, 28, 92, 44, 77])

In [83]:
one_d_arr = ran.randint(5,100,25)  # assiging array ro 'one_d_arr' variable
one_d_arr   # printing the response

array([60,  5, 58, 84,  7, 49, 79, 95, 15, 28, 64, 64, 27, 34, 21, 76, 42,
       72, 55, 18, 66, 82, 25, 72, 61])

In [85]:
one_d_arr.reshape(5,5)  

# re shaping the array into 5*5 Dim

array([[60,  5, 58, 84,  7],
       [49, 79, 95, 15, 28],
       [64, 64, 27, 34, 21],
       [76, 42, 72, 55, 18],
       [66, 82, 25, 72, 61]])

In [88]:
## finding the max and min values

one_d_arr.max()

95

In [87]:
one_d_arr.min()

5

In [ ]:
## finding the index position of max and min numbers 

one_d_arr.argmax()


7

In [90]:
one_d_arr.argmin()

1