# Operators on Arrays

| Operator | Meaning                  | Example    | Result  |
| -------- | ------------------------ | ---------- | ------- |
| `>`      | Greater than             | `5 > 3`    | `True`  |
| `<`      | Less than                | `2 < 7`    | `True`  |
| `>=`     | Greater than or equal to | `4 >= 4`   | `True`  |
| `<=`     | Less than or equal to    | `6 <= 3`   | `False` |
| `==`     | Equal to                 | `10 == 10` | `True`  |
| `!=`     | Not equal to             | `5 != 3`   | `True`  |


In [2]:
# 1Dim array

import numpy as np

one_d_array = np.arange(1,11)

one_d_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# make a new array where the numbers are > 5

one_d_array > 5 

# This will return a list of boolean values like below. if the number is > 5 it returns true else false.


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [8]:
# assigning the result to a variable

bool_array = one_d_array > 5

bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [11]:
one_d_array[bool_array]

# this will display only numbers which are > 5


array([ 6,  7,  8,  9, 10])

## Example 

In [19]:
big_array = np.arange(1,101).reshape(10,10)

big_array

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [25]:
# add,sub,mul,div

big_array+2 

array([[  3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18,  19,  20,  21,  22],
       [ 23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42],
       [ 43,  44,  45,  46,  47,  48,  49,  50,  51,  52],
       [ 53,  54,  55,  56,  57,  58,  59,  60,  61,  62],
       [ 63,  64,  65,  66,  67,  68,  69,  70,  71,  72],
       [ 73,  74,  75,  76,  77,  78,  79,  80,  81,  82],
       [ 83,  84,  85,  86,  87,  88,  89,  90,  91,  92],
       [ 93,  94,  95,  96,  97,  98,  99, 100, 101, 102]])

In [26]:
big_array-2

array([[-1,  0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56, 57, 58],
       [59, 60, 61, 62, 63, 64, 65, 66, 67, 68],
       [69, 70, 71, 72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85, 86, 87, 88],
       [89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [27]:
big_array*2

array([[  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30,  32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50,  52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96,  98, 100],
       [102, 104, 106, 108, 110, 112, 114, 116, 118, 120],
       [122, 124, 126, 128, 130, 132, 134, 136, 138, 140],
       [142, 144, 146, 148, 150, 152, 154, 156, 158, 160],
       [162, 164, 166, 168, 170, 172, 174, 176, 178, 180],
       [182, 184, 186, 188, 190, 192, 194, 196, 198, 200]])

In [28]:
big_array/2

array([[ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ],
       [ 5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ],
       [10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ],
       [15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ],
       [20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. ],
       [25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5, 30. ],
       [30.5, 31. , 31.5, 32. , 32.5, 33. , 33.5, 34. , 34.5, 35. ],
       [35.5, 36. , 36.5, 37. , 37.5, 38. , 38.5, 39. , 39.5, 40. ],
       [40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5, 44. , 44.5, 45. ],
       [45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. , 49.5, 50. ]])

In [29]:
big_array//2

array([[ 0,  1,  1,  2,  2,  3,  3,  4,  4,  5],
       [ 5,  6,  6,  7,  7,  8,  8,  9,  9, 10],
       [10, 11, 11, 12, 12, 13, 13, 14, 14, 15],
       [15, 16, 16, 17, 17, 18, 18, 19, 19, 20],
       [20, 21, 21, 22, 22, 23, 23, 24, 24, 25],
       [25, 26, 26, 27, 27, 28, 28, 29, 29, 30],
       [30, 31, 31, 32, 32, 33, 33, 34, 34, 35],
       [35, 36, 36, 37, 37, 38, 38, 39, 39, 40],
       [40, 41, 41, 42, 42, 43, 43, 44, 44, 45],
       [45, 46, 46, 47, 47, 48, 48, 49, 49, 50]])

In [30]:
big_array%2

array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

In [31]:
(big_array%2) == 0

array([[False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True]])

In [32]:
# Even numbers
big_array[(big_array%2) == 0 ]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [33]:
# Odd numbers
big_array[(big_array%2) != 0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])