# DataFrame

## What is a DataFrame ?
### DataFrame is a bunch of pandas series which shares same index.

In [9]:
# Example on randn function from random package

# The function numpy.random.randn() generates random numbers from the standard normal distribution.

from numpy.random import randn

randn() # This will return 1 random number

-0.8051835193804108

In [10]:
randn(5)  # This will generate 1Dim Matrix of random numbers.

array([ 0.21228006,  0.49235385,  1.66745318, -1.90475993, -0.52030071])

In [11]:
randn(5,5)  # This will generate 5*5 Matrix (2Dim) of random numbers.

array([[-0.43239057,  0.27836227,  0.27090734, -0.91362123,  0.35889997],
       [-0.53508396, -0.95499726,  1.69688074, -0.1117076 , -0.37001188],
       [-0.1012709 , -0.45426876, -0.88492155, -0.31169476, -0.84966467],
       [ 0.97847237,  0.66159202,  0.46084992, -0.05269805, -2.89921773],
       [ 2.23442374,  0.66670258,  1.33828423,  0.18510509,  2.61107548]])

In [14]:
randn(2,3,4)  # This will generate Multi Dim Matrix of random numbers.

array([[[-1.39916188, -1.21039515, -0.35705464, -0.27541011],
        [-0.56213202,  1.23688894,  0.30722755,  1.1112549 ],
        [-1.02575962, -2.95381836,  1.11045506, -0.11439082]],

       [[-0.47633318,  0.02132433, -0.05919265, -0.42729137],
        [ 0.1986105 ,  0.40748948, -1.52412784, -0.6310939 ],
        [-0.62256199,  0.05856904, -0.93039511,  1.32325277]]])

#### randn function Parameters:
d0, d1,......., dn  --  int, optional

    The dimensions of the returned array, must be non-negative. If no argument is given a single Python float is returned.

#### randn function Returns :
ndarray or float
    
    A (d0, d1, ..., dn)-shaped array of floating-point samples from the standard normal distribution, or a single such float if no parameters were supplied.

## Creating a DataFrame object

####  pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None)

In [58]:
import pandas as pd

# Creating a dataframe object and assigning to df variable

df = pd.DataFrame(data=randn(5,5), index=['A','B','C','D','E'], columns=['Z','Y','X','W','V'])

df

Z         Y         X         W         V
A -0.486400 -1.161892  2.685931 -0.625476  0.433312
B  0.410998  0.052810  0.963016 -0.168864  1.606999
C -0.538373 -0.890497 -1.126993  0.373924  0.062922
D -0.104495  1.059294  1.267068  1.276866 -0.222680
E -1.064115  0.817193 -0.710931  0.964350 -0.006634

#### Finding type of df object is

In [59]:
type(df)  # DataFrame Object

pandas.core.frame.DataFrame

In [60]:
# reading only z column values

print(df['Z'])

A   -0.486400
B    0.410998
C   -0.538373
D   -0.104495
E   -1.064115
Name: Z, dtype: float64


In [61]:
# reading only z column values

# df['Z'] is also written as df.Z

print(df.Z)

A   -0.486400
B    0.410998
C   -0.538373
D   -0.104495
E   -1.064115
Name: Z, dtype: float64


### Note :  Print type of 1 colum

In [62]:
type(df.Z)

pandas.core.series.Series

📌 📌 📌 📌 <b><span style="color:red;">It's printing type of a row as a Series. It means DataFrame is a bunch of Series which share same index.</span></u></b> ✅ 

In [63]:
# reading multiple columns 

result = df[['Z','X']]

result

Z         X
A -0.486400  2.685931
B  0.410998  0.963016
C -0.538373 -1.126993
D -0.104495  1.267068
E -1.064115 -0.710931

### Note :  Print type of Multiple colum

In [64]:
type(result)

pandas.core.frame.DataFrame

In [65]:
df.shape

(5, 5)

### For above created DataFrame we can see the sahpe as

🔥🔥 <b><span style="color:Green;"> Underastand the shape of DataFrame</span></u></b> 

(5, 5)

5 - Rows 
5 - colums 

#### Note : 
    1. The position of 5(Row) in tuple is Zero (0).
    2. The position of 5(col) in tuple is One (1).

####  To Remove a row from a Dataframe we use drop function.

    DataFrame.drop(labels=None, *, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise')[source]

In [66]:
df

Z         Y         X         W         V
A -0.486400 -1.161892  2.685931 -0.625476  0.433312
B  0.410998  0.052810  0.963016 -0.168864  1.606999
C -0.538373 -0.890497 -1.126993  0.373924  0.062922
D -0.104495  1.059294  1.267068  1.276866 -0.222680
E -1.064115  0.817193 -0.710931  0.964350 -0.006634

## Removing Col and Row

In [67]:
# removing W column

df.drop('W') #  This will return error because by default the axis is Zero it means, the drop function is searching in rown not cols .
             #  as per the DATAFRAME shape the colum i 1 and rows are 0.
             #  so we need to pass axis = 1

KeyError: "['W'] not found in axis"

In [68]:
# removing W column

df.drop('W',axis=1) #  This will return error because by default the axis is Zero it means, the drop function is searching in rown not cols .
             #  as per the DATAFRAME shape the colum i 1 and rows are 0.
             #  so we need to pass axis = 1

Z         Y         X         V
A -0.486400 -1.161892  2.685931  0.433312
B  0.410998  0.052810  0.963016  1.606999
C -0.538373 -0.890497 -1.126993  0.062922
D -0.104495  1.059294  1.267068 -0.222680
E -1.064115  0.817193 -0.710931 -0.006634

### ❗❗❗Note❗❗❗ : is column 'W' deleted ..?

### Ans is 💥'NO'💥..  Its just droped not deleted permanently.

In [69]:
df  #  if you check the below response still we can see 'W' col.

Z         Y         X         W         V
A -0.486400 -1.161892  2.685931 -0.625476  0.433312
B  0.410998  0.052810  0.963016 -0.168864  1.606999
C -0.538373 -0.890497 -1.126993  0.373924  0.062922
D -0.104495  1.059294  1.267068  1.276866 -0.222680
E -1.064115  0.817193 -0.710931  0.964350 -0.006634

### 🔔🔔🔔To Delete it permanently we need to pass 'inplace=True' Parameter.

In [70]:
df.drop('W',axis=1,inplace=True)

In [71]:
df

Z         Y         X         V
A -0.486400 -1.161892  2.685931  0.433312
B  0.410998  0.052810  0.963016  1.606999
C -0.538373 -0.890497 -1.126993  0.062922
D -0.104495  1.059294  1.267068 -0.222680
E -1.064115  0.817193 -0.710931 -0.006634

In [72]:
# removing C row

df.drop('C') #  This will not return any error because by default the axis is Zero it means.
             #  In the DATAFRAME shape the colum i 1 and rows are 0.
             #  By default the axis is Zero, so no need to pass.

Z         Y         X         V
A -0.486400 -1.161892  2.685931  0.433312
B  0.410998  0.052810  0.963016  1.606999
D -0.104495  1.059294  1.267068 -0.222680
E -1.064115  0.817193 -0.710931 -0.006634

###  ‼️  Note ‼️  Same as col we need to pass inplace to delete row permanently.

In [73]:
df

Z         Y         X         V
A -0.486400 -1.161892  2.685931  0.433312
B  0.410998  0.052810  0.963016  1.606999
C -0.538373 -0.890497 -1.126993  0.062922
D -0.104495  1.059294  1.267068 -0.222680
E -1.064115  0.817193 -0.710931 -0.006634

In [74]:
df.drop('C',inplace=True)

In [75]:
df

Z         Y         X         V
A -0.486400 -1.161892  2.685931  0.433312
B  0.410998  0.052810  0.963016  1.606999
D -0.104495  1.059294  1.267068 -0.222680
E -1.064115  0.817193 -0.710931 -0.006634

## Adding a new Column

In [76]:
df['Sum(Z+Y)'] = df['Z'] + df ['Y']  #  Note: The new col name is "Sum(Z+Y)" we can name anything...!

In [77]:
df  

Z         Y         X         V  Sum(Z+Y)
A -0.486400 -1.161892  2.685931  0.433312 -1.648291
B  0.410998  0.052810  0.963016  1.606999  0.463809
D -0.104495  1.059294  1.267068 -0.222680  0.954798
E -1.064115  0.817193 -0.710931 -0.006634 -0.246922

## Reading Col

In [80]:
## Reading 'X' Column from DataFrame Object.

df.X

A    2.685931
B    0.963016
D    1.267068
E   -0.710931
Name: X, dtype: float64

In [81]:
## Reading 'V' Column from DataFrame Object.

df.V

A    0.433312
B    1.606999
D   -0.222680
E   -0.006634
Name: V, dtype: float64

In [82]:
## Reading 'Sum(Z+Y)' Column from DataFrame Object.

df.Sum(Z+Y)  # This is assuming the Sum as function so try using df['Sum(Z+Y)']

AttributeError: 'DataFrame' object has no attribute 'Sum'

In [83]:
## Reading 'Sum(Z+Y)' Column from DataFrame Object.

df['Sum(Z+Y)']

A   -1.648291
B    0.463809
D    0.954798
E   -0.246922
Name: Sum(Z+Y), dtype: float64

## Reading Row

In [84]:
# To read a row we use "loc" 

df.loc['A']

Z          -0.486400
Y          -1.161892
X           2.685931
V           0.433312
Sum(Z+Y)   -1.648291
Name: A, dtype: float64

In [88]:
# "iloc" -- 'i' stands for index

df.iloc[0]

Z          -0.486400
Y          -1.161892
X           2.685931
V           0.433312
Sum(Z+Y)   -1.648291
Name: A, dtype: float64

In [89]:
####  Note : The both outputs are same.

In [92]:
df.iloc[:2]

Z         Y         X         V  Sum(Z+Y)
A -0.486400 -1.161892  2.685931  0.433312 -1.648291
B  0.410998  0.052810  0.963016  1.606999  0.463809

In [94]:
df.iloc[::-1]  # in reverse order.

Z         Y         X         V  Sum(Z+Y)
E -1.064115  0.817193 -0.710931 -0.006634 -0.246922
D -0.104495  1.059294  1.267068 -0.222680  0.954798
B  0.410998  0.052810  0.963016  1.606999  0.463809
A -0.486400 -1.161892  2.685931  0.433312 -1.648291

In [97]:
df.loc['A','X']  # Reading only 1 shell value.

np.float64(2.6859308410918197)

In [100]:
df.loc[['A','D','B'],['X']]

X
A  2.685931
D  1.267068
B  0.963016

In [101]:
df.loc[['A','D'],['X','Y','Z']]

X         Y         Z
A  2.685931 -1.161892 -0.486400
D  1.267068  1.059294 -0.104495

In [102]:
df.loc[['A'],['X','Y','Z']]

X         Y       Z
A  2.685931 -1.161892 -0.4864